#!/usr/bin/python
# -*- encoding: utf-8 -*-

#
# 'generate_vsm_scimu'
# 
# Copyright (C) 2013 Jorge Couchet <jorge.couchet at gmail.com>
#
# This file is part of 'ted-scimu'
# 
# 'ted-scimu' is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# 'ted-scimu' is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with 'ted-scimu'.  If not, see <http ://www.gnu.org/licenses/>.
#

import text_augmentation
import generate_vsm

FROM_TFID_MODEL_FILENAME = 'gen_data/sc-ind'
FILENAME_FOR_AUGMENTATED_LOG = 'gen_data/docs_augmentated'

IS_TED = True
IS_NOUN = True
CORPUS_FOLDER = 'rel_scimu'
IS_GEN_DICT = False
IS_TFIDF = True
MIN_TFIDF_WEIGHT = 0.05
FILENAME = 'gen_data/sc1'
FILENAME_DICT_FROM_TED = 'gen_data/t1'


if __name__ == "__main__":

    texts_for_augmentation = text_augmentation.augment_corpus_information(FROM_TFID_MODEL_FILENAME, FROM_TFID_MODEL_FILENAME, FROM_TFID_MODEL_FILENAME, FROM_TFID_MODEL_FILENAME, FILENAME_FOR_AUGMENTATED_LOG)

    # It is generating the Science Museum corpus representation in the TED talks VSM, for this reason the dictionary to be used must be the TED Talks
    # dictionary
    # --
    # It is augmenting the texts with annotation 's abstracts from the Dbpedia
    generate_vsm.tokenize(IS_TED, IS_NOUN, CORPUS_FOLDER, FILENAME, IS_GEN_DICT, FILENAME_DICT_FROM_TED, FILENAME, IS_TFIDF, MIN_TFIDF_WEIGHT, FILENAME, texts_for_augmentation)
